version: '2.1'

services:
  opal-logging-service:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/opal/logging-service
    environment:
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false
      - OPAL_LOGGING_DB_HOST=opal-logging-db
      - OPAL_LOGGING_DB_PORT=5432
      - OPAL_LOGGING_DB_NAME=opal-logging-db
      - OPAL_LOGGING_DB_USERNAME=opal-logging
      - OPAL_LOGGING_DB_PASSWORD=opal-logging
    ports:
      - $SERVER_PORT:$SERVER_PORT
  opal-logging-db:
    container_name: opal-logging-db
    image: postgres:18.0
    restart: always
    environment:
      - POSTGRES_DB=opal-logging-db
      - POSTGRES_USER=opal-logging
      - POSTGRES_PASSWORD=opal-logging
      - PGPORT=5432
    ports:
      - "5436:5432"
    volumes:
      - opal_logging_db_data:/var/lib/postgresql/data

volumes:
  opal_logging_db_data:
